Fix accessibility of _mlEnabled field in nudge-tray
Change _mlEnabled from private to internal static to allow access
from the App class when creating the tray menu.

Fixes compilation error:
  error CS0122: 'Program._mlEnabled' is inaccessible due to its protection level